### ISSUE TITLE
Multiple Queries in 1 Panel

### ISSUE THREAD

**Issue by Mastermind497** [grafana/mqtt-datasource#78]
When using multiple queries in a single panel, it seems like you aren't able to treat the queries separately (say, if I want to scale each query by a different amount and add them together, or if I want to change the label on two different queries to two different things):

![Screenshot from 2023-06-01 11-41-24](https://github.com/grafana/mqtt-datasource/assets/39387439/c36fef04-c92d-4922-8fff-eb70ef3fe739)
![Screenshot from 2023-06-01 11-41-37](https://github.com/grafana/mqtt-datasource/assets/39387439/99d2d3d8-0e06-4db5-8ede-89735f31a07a)

**Comment by Mastermind497** [comment]
This functionality is fixed now

**Comment by Mayerch1** [comment]
@Mastermind497 I'm using the plugin in version `1.0.0-beta.3` on Grafana `Grafana v10.2.3` and I can't get this working.
While the dropdown is now returning data, I still can't distinguish between multiple queries.

All queries are shown as a single entity.

![grafik](https://github.com/grafana/mqtt-datasource/assets/28509096/6ab14d8c-0cc2-4875-b797-22b5ea805f94)
![grafik](https://github.com/grafana/mqtt-datasource/assets/28509096/f6677441-b279-4b9c-8ef7-c42aad77991e)

While I can override all queries using this approach, it isn't helpful for overriding specific attributes.
